### ISSUE TITLE
Download rate limit does not seem to work

### ISSUE THREAD

**Issue by bsergean** [anacrolix/torrent#447]
This is probably a mistake on my side

```
$ go run cmd/torrent/main.go download --downloadrate 1000000 /tmp/my.torrent
2020-12-17T12:09:03-0800 NONE  client.go:1318: won't add DHT node with bad IP: ""
2020-12-17T12:09:03-0800 NONE  client.go:1318: won't add DHT node with bad IP: "example.com"
downloading "/tmp/my.torrent": 231 MB/983 MB, 55/235 pieces completed (0 partial)
downloading "/tmp/my.torrent": 236 MB/983 MB, 55/235 pieces completed (4 partial)
2020-12-17T12:09:05-0800 NONE  portfwd.go:30: discovered 0 upnp devices
downloading "/tmp/my.torrent": 242 MB/983 MB, 55/235 pieces completed (5 partial)
downloading "/tmp/my.torrent": 247 MB/983 MB, 55/235 pieces completed (6 partial)
downloading "/tmp/my.torrent": 253 MB/983 MB, 58/235 pieces completed (6 partial)
downloading "/tmp/my.torrent": 258 MB/983 MB, 59/235 pieces completed (6 partial)
downloading "/tmp/my.torrent": 263 MB/983 MB, 60/235 pieces completed (5 partial)
downloading "/tmp/my.torrent": 269 MB/983 MB, 63/235 pieces completed (3 partial)
```

I would expect `--downloadrate 1000000` to max out download rate at 1M/s, but here we go at 5M/s or 6M/s.

This is what the cmd does to control the rate limiter.
```
		clientConfig.DownloadRateLimiter = rate.NewLimiter(rate.Limit(flags.DownloadRate), 1<<20)
```

I tried changing 	

```
clientConfig.DisableAcceptRateLimiting = true
```

to false without success.

I see it used in this function, but the 'Accept' makes me think about unix accept syscall for a server config, so maybe that options isn't relevant.

```
func (cl *Client) rateLimitAccept(ip net.IP) bool {
    if cl.config.DisableAcceptRateLimiting {
        return false
    }
    return cl.acceptLimiter[ipStr(maskIpForAcceptLimiting(ip).String())] > 0
}
```

Lastly, are those errors problematic, or related ?

```
2020-12-17T12:09:03-0800 NONE  client.go:1318: won't add DHT node with bad IP: ""
2020-12-17T12:09:03-0800 NONE  client.go:1318: won't add DHT node with bad IP: "example.com"
```

Thanks for any help !

**Comment by anacrolix** [comment]
The accept rate limiting is different, you can ignore that. I've added a doc comment for it.

It might be possible to see bursts of higher download rates for short periods, particularly if there's a lot of connection turnover, or very large read buffers, although that shouldn't be represented in the status output line, as the incoming data is n't processed until the appropriate delay is applied.

Are you running with any custom transports, or using WebRTC/WebTorrent connections?

**Comment by bsergean** [comment]
I think I'm using a normal transfer (TCP), I have UTP disabled. The peers/seed should be using the original libtorrent C++ library.

The files to download are rather large (~1G / 900M).

**Comment by anacrolix** [comment]
@bsergean it might help to have the metainfo or magnet link you're testing with, so I can verify if the protocols used aren't being rate-limited. You can send that to me privately if preferred.

**Comment by bsergean** [comment]
Unfortunately the torrrents aren’t public, and are used to fetch internal data so I don’t know if you could use them. But maybe just the .torrent or meta info file would be enough ?

Thanks for the help btw ; I’m not actively working on this those days which why I haven’t checked in recently.

**Comment by anacrolix** [comment]
The metainfo might be enough, if you can share it. Thanks

**Comment by bsergean** [comment]
panic: subsequent listen: listen udp4 :42069: bind: address already in use

Trying to print/get the .torrent file but now I keep on getting that error (after I did cancelled a download)

**Comment by anacrolix** [comment]
Sorry I missed this. You could run with `-addr=:0` to ensure you get a free port. The error you're describing would indicate that you already have a torrent client running on the default port.

**Comment by bsergean** [comment]
Thanks I’ll give this a try when I get a chance.

**Comment by anacrolix** [comment]
I did some testing and tidying around the rate limits. I definitely think it's working, my best guess would be some bursty behaviour or lag between updates to the progress that's emitted. I've implemented a fix for that in https://github.com/anacrolix/torrent/commit/8706d326bac7f7f5a1f021620718e1cc4ad77cee.

**Comment by bsergean** [comment]
Cool, I’m gonna try that today.

Here is the function I use for downloading, it has a time.Sleep which you don’t have in your sample anymore.

func downloadFileWithTorrent(httpClient *http.Client, client *torrent.Client,
    url string, torrentPath string) error {
    // Fetch torrent
    response, err := httpClient.Get(url)
    if err != nil {
        return fmt.Errorf("Error downloading torrent file %s: %s\n", url, err)
    }

    // Read the response body into a string
    torrentContent, err := ioutil.ReadAll(response.Body)
    if err != nil {
        return err
    }

    // Write the torrent to disk
    err = ioutil.WriteFile(torrentPath, torrentContent, 0644)
    if err != nil {
        return err
    }

    // Load the torrent from disk into our torrent client
    metaInfo, err := metainfo.LoadFromFile(torrentPath)
    if err != nil {
        return fmt.Errorf("Error loading torrent file %s: %s\n", torrentPath, err)
    }

    // Add the torrent for subsequent download
    torrent, err := client.AddTorrent(metaInfo)
    if err != nil {
        log.Printf("Error adding torrent file %s: %s\n", url, err)
        return err
    }

    // display progress report when a torrent file is downloaded
    bar := pb.StartNew(int(torrent.Length()))
    bar.Set(pb.Bytes, true)
    bar.Start()

    go func() {
        for {
            bar.SetCurrent(torrent.BytesCompleted())
            time.Sleep(time.Second)
        }
    }()

    torrent.DownloadAll()

    if client.WaitAll() {
        log.Print("downloaded all torrents")
    } else {
        bar.Finish()
        return errors.New("The torrent files were not downloaded")
    }

    bar.Finish()
    return nil
}

**Comment by bsergean** [comment]
I still can’t make this work, but I think the problem is on my end.

With this:

    defaultRateLimit := 1 << 10
    rateLimit := defaultRateLimit
    clientConfig.DownloadRateLimiter = rate.NewLimiter(rate.Limit(rateLimit), defaultRateLimit)

I can’t get rate limit to work. The problem is likely on my end though as I got this snippet from the main.go cmd/torrent file.

**Comment by bsergean** [comment]
I think I wasted enough of your time so I'm gonna close this.

**Comment by anacrolix** [comment]
No worries.
